version: '3.7'
services:
  php-apache:
    container_name: php-apache
    restart: always
    build: .
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql-db
    ports:
      - '8000:80'

  mysql-db:
    container_name: mysql-db
    image: mysql
    restart: always
    env_file:
      - config.env
    ports:
      - '9906:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8100:80'
    restart: always
    environment:
      PMA_HOST: mysql-db
    depends_on:
      - mysql-db
